language: python

matrix:
  include:
    - python: "2.7"
install: 
  #### install PySide
  - sudo apt-get install libqt4-dev
  - travis_wait pip install --find-links https://parkin.github.io/python-wheelhouse/ --use-wheel PySide;
  # Finish the PySide install, since we are in a virtualenv
  - python ~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py -install
  # Setup coverage and the development mode
  - pip install coveralls
  - "python setup.py develop"

before_script:
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script: 
  - nosetests --cover-erase --with-coverage --cover-package=bluegraph

notifications:
  email: false
