language: python
python:
- '2.7'
install:
  - pip install coveralls
  - "python setup.py develop"
before_script:
  - export DISPLAY=:99
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script: nosetests --cover-erase --with-coverage --cover-package=bluegraph
after_success: coveralls
