language: python
python:
- '2.7'
install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev python-qt4 pyqt4-dev-tools qt4-designer
  - pip install coveralls
  - "python setup.py develop"
script: nosetests --cover-erase --with-coverage --cover-package=bluegraph --exclude=scripts/
after_success: coveralls
