language: python
python:
- '2.7'
install:
  - pip install pyqt4
  - pip install coveralls
  - "python setup.py develop"
script: nosetests --cover-erase --with-coverage --cover-package=bluegraph --exclude=scripts/
after_success: coveralls
