sudo: false
language: python
addons:
  apt:
    packages:
    - python-qt4
python:
- '2.7'
install:
  - pip install coveralls
  - "python setup.py develop"
script: nosetests --cover-erase --with-coverage --cover-package=bluegraph --exclude=scripts/
after_success: coveralls
